# Generated by Django 6.0 on 2025-12-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('editorial', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEjemplar', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('prestado', 'Prestado'), ('disponible', 'Disponible'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='inventario.libro')),
            ],
        ),
    ]
