# Generated by Django 6.0 on 2025-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
