# Generated by Django 6.0 on 2025-12-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipousuario'),
        ),
    ]
