# Generated by Django 5.2.8 on 2025-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('bibliotecario', 'Bibliotecario'), ('administrador', 'Administrador')], default='alumno', max_length=20),
        ),
    ]
