# Generated by Django 5.2.8 on 2025-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='diaMaxRenovacion',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='diasPrestamoMin',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
