# Generated by Django 6.0 on 2025-12-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_lector_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
