# Generated by Django 5.2.8 on 2025-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tipousuario_diamaxrenovacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='cantidadPrestamosMax',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
