# Generated by Django 5.2.8 on 2025-12-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tipousuario_cantidadprestamosmax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='cantidadPrestamosMax',
        ),
    ]
