# Generated by Django 5.2.8 on 2025-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_tipousuario_cantidadprestamosmax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='diaMaxRenovacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
