# Generated by Django 5.2.8 on 2025-12-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_tipousuario_diamaxrenovacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='idEncargado',
        ),
        migrations.AddField(
            model_name='encargado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
