# Generated by Django 6.0 on 2025-12-11 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('idMulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('diasRetraso', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoPago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('atrasado', 'Atrasado')], default='activo', max_length=20)),
                ('renovacionesUtilizadas', models.IntegerField(default=0)),
                ('codigoEjemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ejemplar')),
            ],
        ),
    ]
