# Generated by Django 5.2.8 on 2025-12-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.lector'),
        ),
        migrations.AddField(
            model_name='multa',
            name='idPrestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.prestamo'),
        ),
    ]
