# Generated by Django 6.0 on 2025-12-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.libro'),
            preserve_default=False,
        ),
    ]
