# Generated by Django 6.0 on 2025-12-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_libro_habilitado'),
        ('ops', '0002_initial'),
        ('usuarios', '0002_alter_lector_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='codigoEjemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ejemplar'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.lector'),
        ),
    ]
