# Generated by Django 5.2.8 on 2025-12-09 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_prestamo_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='fechaMulta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
