# Generated by Django 6.0 on 2025-12-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_prestamo_codigoejemplar_alter_prestamo_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='dias_prestamo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
